name: CI

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'REDME.MD'
            - 'helm/**'

jobs:
   
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v4

            - name: Set up Go 1.23
              uses: actions/setup-go@v2
              with:
                go-version: 1.23

            - name: Build
              run: go build -o go-web-app
        
            - name: Test 
              run: go test ./..
    
    code-quality:
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v6   # this is static code analyses
              with:
                version: v1.56.2
    push:
      runs-on: ubuntu-latest

      needs: build

      steps:
        - name: checkout repository
          uses: actions/checkout@v4

        - name: Set up docker bvuildx
          uses: docker/setup-buildx-action@v1

        - name: Login to docker hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Build and push action
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}

    update-newtag-in-helm-chart:
      runs-on: ubuntu-latest

      steps:
        - name: checkout repository
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.TOKEN }}

        - name: Update tag in helm chart 
          run: |
            sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yml

        - name: Commit and push changes
          run: |
            git config --global user.email "silentknight.www@gmail.com"
            git config --global user.name "silenknight2001"
            git add helm/go-web-app-chart/values.yml
            git commit -m "Updated tag in helm chart"
            git push





        

